version: "3.8"
networks:
  proxy:
    external: 
      name: proxy
services:
  nexus:
    container_name: nexus
    user: "200"
    image: sonatype/nexus3:3.34.1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
          memory: 2048M
        reservations:
          memory: 2048M
    ports:
      - "8081:8081"
    environment: 
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    healthcheck:
      test: curl -fsSL http://localhost:8081/COPYRIGHT.html || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
    volumes:
      - $PWD/nexus-data:/nexus-data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
        tag: "{{.DaemonName}}.{{.ImageName}}"
    networks:
      proxy: