version: "3.8"
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    environment: 
      - TZ=America/Sao_Paulo
      - update=1
    networks:
      - proxy
    volumes:
      - $PWD/nginx-whoami.conf:/etc/nginx/conf.d/default.conf
networks:
  proxy:
    name: proxy
    external: true