services:
  nginx:
    image: nginx:stable
    hostname: nginx
    entrypoint:
      - '/bin/sh'
      - '-c'
    command: 
      - |
        cat <<'EOF'> /etc/nginx/conf.d/default.conf
        server_tokens off;
        server {
          listen       80;
          server_name  _;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            default_type text/plain;
            expires -1;
            return 200 'Server address: $$server_addr:$$server_port\nServer name: $$hostname\nDate: $$time_local\nURI: $$request_uri\nRequest ID: $$request_id\n';
          }
          error_page 401 403 404 @40x;
          location @40x {
            default_type text/html;
            return 404 "<html>\n<head><title>Not Found!</title></head>\n<body>\n<center><h1>Not Found!</h1></center>\n</body>\n</html>\n";
          }
          error_page 500 502 503 504 @50x;
          location @50x {
            default_type text/html;
            return 500 "<html>\n<head><title>Internal Server Error!</title></head>\n<body>\n<center><h1>Internal Server Error!</h1></center>\n</body>\n</html>\n";
          }
        }
        EOF
        #exec tail -f /dev/null
        exec nginx -g 'daemon off;'
    environment:
      - update=3
      - TZ=America/Sao_Paulo
    ports:
      - 0:80
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
          memory: 256M
        reservations:
          memory: 256M
    restart: unless-stopped
    network_mode: bridge
  busybox:
    container_name: busybox
    image: busybox
    entrypoint:
      - '/bin/sh'
      - '-c'
    command: 
      - |
        tail -f /dev/null &
        pid="$$!"
        echo "Starting PID $$pid"
        trap "echo 'Stopping PID $$pid'; kill -TERM $$pid && exit 0" INT TERM
        wait
    environment:
      - update=3
      - TZ=America/Sao_Paulo
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
          memory: 32M
        reservations:
          memory: 32M
    restart: unless-stopped
    network_mode: service:nginx