version: "3"
networks:
  traefik:
    external: 
      name: traefik
services:
#-----------------------------------
  ldap-server:
    image: ldap-server
    hostname: ldap-server
    container_name: ldap-server
    #tty: true
    ports:
      - 389:389/tcp
    environment: 
      - TZ=America/Sao_Paulo
      - LOGSPOUT=ignore
    volumes:
      - $PWD/slapd.d:/etc/ldap/slapd.d
      - $PWD/ldap:/var/lib/ldap
    healthcheck:
      test: ldapsearch -x -LLL -H ldap://127.0.0.1 -ZZ -b dc=example,dc=com || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "7"
        max-size: "10m"
        tag: "ldap-server"
    networks:
      traefik:
