version: "3.8"
services:
  dind:
    image: dind:latest
    build:
      dockerfile: Dockerfile
      context: .
    container_name: dind
    hostname: dind
    privileged: true
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
          memory: 256M
        reservations:
          memory: 128M
    restart: "unless-stopped"
    environment: 
      - TZ=America/Sao_Paulo
networks:
  proxy:
    name: proxy
    external: true
