- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  handlers:
    - name: 'restart rsyslog'
      service:
        name: rsyslog
        state: restarted
    - name: 'reload haproxy'
      service:
        name: haproxy
        state: reloaded
  tasks:
    - name: 'install packages'
      apt:
        name: "{{ packages }}"
        update_cache: no
      vars:
        packages:
        - linux-virtual-hwe-20.04
        - haproxy
        - ssl-cert

    - name: '/etc/haproxy/certs'
      file: 
        path: "/etc/haproxy/certs"
        state: directory

    - name: 'check ssl-cert-snakeoil'
      shell: test -f /etc/haproxy/certs/ssl-cert-snakeoil.pem
      register: snakeoil_check
      failed_when: snakeoil_check.rc > 1
      changed_when: snakeoil_check.rc > 0

    - name: 'ssl-cert-snakeoil'
      shell: |
        cat /etc/ssl/certs/ssl-cert-snakeoil.pem /etc/ssl/private/ssl-cert-snakeoil.key > /etc/haproxy/certs/ssl-cert-snakeoil.pem
      when: snakeoil_check.rc > 0

    - name: 'Sysctl Conf'
      sysctl:
        name: "{{item}}"
        value: '1'
        sysctl_file: /etc/sysctl.d/999-custom.conf
        reload: yes
      with_items:
        - net.ipv4.ip_nonlocal_bind

    - name: '/etc/haproxy/haproxy.cfg'
      copy:
        dest: /etc/haproxy/haproxy.cfg
        backup: yes
        content: |
          global
              log /dev/log    local0
              log /dev/log    local1 notice
              chroot /var/lib/haproxy
              stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
              stats timeout 30s
              user haproxy
              group haproxy
              daemon
              # Default SSL material locations
              ca-base /etc/ssl/certs
              crt-base /etc/ssl/private
              # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
              ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
              ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
              ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets
              tune.ssl.default-dh-param 2048
          defaults
              log     global
              mode    http
              option  httplog
              option  dontlognull
              timeout connect 5000
              timeout client  50000
              timeout server  50000
              errorfile 400 /etc/haproxy/errors/400.http
              errorfile 403 /etc/haproxy/errors/403.http
              errorfile 408 /etc/haproxy/errors/408.http
              errorfile 500 /etc/haproxy/errors/500.http
              errorfile 502 /etc/haproxy/errors/502.http
              errorfile 503 /etc/haproxy/errors/503.http
              errorfile 504 /etc/haproxy/errors/504.http
          resolvers dns-proxy
              nameserver mydns 127.0.0.1:5353
              accepted_payload_size 8192
              hold valid 5s
              resolve_retries 30
              timeout retry 2s
          frontend web
              bind 0.0.0.0:80 name http
              bind 0.0.0.0:443 name https ssl crt /etc/haproxy/certs/ ssl-min-ver TLSv1.2
              #http-response set-header Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"
              #http-request redirect scheme https unless { ssl_fc }
              #http-request redirect scheme https code 301 unless { ssl_fc }
              mode http
              default_backend whoami
              option forwardfor
              option dontlog-normal
              http-request capture req.hdr(Host) len 10
              http-request capture req.hdr(User-Agent) len 100
              acl is_stats path_beg /stats
              use_backend stats if is_stats
              #PORTAINER
              acl use-portainer hdr_end(host) -i portainer.example.com
              use_backend portainer if use-portainer
              #NEXUS
              acl use-nexus hdr_end(host) -i nexus.example.com
              use_backend nexus if use-nexus
              #REGISTRY
              acl use-registry hdr_end(host) -i registry.example.com
              use_backend registry if use-registry
              #JENKINS
              acl use-jenkins hdr_end(host) -i jenkins.example.com
              use_backend jenkins if use-jenkins
              #GITLAB
              acl use-gitlab hdr_end(host) -i gitlab.example.com
              use_backend gitlab if use-gitlab
          backend stats
              server stats 127.0.0.1:2080/stats
          listen Stats
              bind 127.0.0.1:2080
              mode http
              stats enable
              stats hide-version
              stats uri /stats
              stats show-legends
              no log
          backend whoami
              mode http
              balance leastconn
              option http-keep-alive
              option httpchk GET /
              http-check expect status 200
              option forwardfor except 127.0.0.1
              server-template whoami- 1 whoami.proxy:80 check resolvers dns-proxy init-addr libc,none
              http-request set-header X-Real-IP %[src]
              http-request set-header X-Forwarded-Host %[req.hdr(Host)]
              http-request set-header X-Forwarded-Port %[dst_port]
              http-request set-header X-Forwarded-Proto https if { ssl_fc }
              http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
          backend portainer
              mode http
              balance leastconn
              option http-keep-alive
              option httpchk GET /
              http-check expect status 200
              option forwardfor except 127.0.0.1
              server-template portainer- 1 portainer.proxy:9000 check resolvers dns-proxy init-addr libc,none
              http-request set-header X-Real-IP %[src]
              http-request set-header X-Forwarded-Host %[req.hdr(Host)]
              http-request set-header X-Forwarded-Port %[dst_port]
              http-request set-header X-Forwarded-Proto https if { ssl_fc }
              http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
          backend nexus
              mode http
              balance leastconn
              option http-keep-alive
              option httpchk GET /COPYRIGHT.html
              http-check expect status 200
              option forwardfor except 127.0.0.1
              server-template nexus- 1 nexus.proxy:8081 check resolvers dns-proxy init-addr libc,none
              http-request set-header X-Real-IP %[src]
              http-request set-header X-Forwarded-Host %[req.hdr(Host)]
              http-request set-header X-Forwarded-Port %[dst_port]
              http-request set-header X-Forwarded-Proto https if { ssl_fc }
              http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
          backend registry
              mode http
              balance leastconn
              option http-keep-alive
              option httpchk GET /v2/
              http-check expect status 401
              option forwardfor except 127.0.0.1
              server-template nexus- 1 nexus.proxy:5000 check resolvers dns-proxy init-addr libc,none
              http-request set-header X-Real-IP %[src]
              http-request set-header X-Forwarded-Host %[req.hdr(Host)]
              http-request set-header X-Forwarded-Port %[dst_port]
              http-request set-header X-Forwarded-Proto https if { ssl_fc }
              http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
          backend jenkins
              mode http
              balance leastconn
              option http-keep-alive
              option httpchk GET /login
              http-check expect status 200
              option forwardfor except 127.0.0.1
              server-template jenkins- 1 jenkins.proxy:8080 check resolvers dns-proxy init-addr libc,none
              http-request set-header X-Real-IP %[src]
              http-request set-header X-Forwarded-Host %[req.hdr(Host)]
              http-request set-header X-Forwarded-Port %[dst_port]
              http-request set-header X-Forwarded-Proto https if { ssl_fc }
              http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
          backend gitlab
              mode http
              balance leastconn
              option http-keep-alive
              option httpchk GET /login
              http-check expect status 200
              option forwardfor except 127.0.0.1
              server-template gitlab- 1 gitlab.proxy:80 check resolvers dns-proxy init-addr libc,none
              http-request set-header X-Real-IP %[src]
              http-request set-header X-Forwarded-Host %[req.hdr(Host)]
              http-request set-header X-Forwarded-Port %[dst_port]
              http-request set-header X-Forwarded-Proto https if { ssl_fc }
              http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
        mode: 0644
        owner: root
        group: root
        validate: haproxy -c -f %s
      notify: reload haproxy