version: "3.8"
networks:
  proxy:
    external: 
      name: proxy
services:
  jenkins:
    image: registry.example.com/jenkins
    build:
      dockerfile: Dockerfile
      context: .
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
          memory: 2048M
        reservations:
          memory: 2048M
    restart: unless-stopped
    ports:
      - 8080:8080
    #   - 50000:50000
    container_name: jenkins
    volumes:
      - $PWD/jenkins:/var/jenkins_home
      - /etc/ssl/example_ca/example_ca.pem:/etc/docker/certs.d/registry.example.com/ca.crt
      - /etc/hosts:/etc/hosts
      #- /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - TZ=America/Sao_Paulo
      # - DOCKER_HOST=tcp://docker:237
      # - DOCKER_CERT_PATH=/certs/client
      # - DOCKER_TLS_VERIFY=1
    healthcheck:
      test: curl --fail -s http://localhost:8080/login || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
        tag: "{{.DaemonName}}.{{.ImageName}}"
    networks:
      proxy:
