version: "3.7"
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:4.2
    restart: unless-stopped
    environment: 
      - TZ=America/Sao_Paulo 
      - PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - graylog
    volumes:
      - mongo_data:/data/db
    logging:
      driver: "journald"
      options:
        tag: "{{.DaemonName}}/{{.Name}}/{{.ID}}"
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    restart: unless-stopped
    environment: 
      - TZ=America/Sao_Paulo
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - LOGSPOUT=ignore
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - graylog
    volumes:
      - es_data:/usr/share/elasticsearch/data
    logging:
      driver: "journald"
      options:
        tag: "{{.DaemonName}}/{{.Name}}/{{.ID}}"
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    deploy:
      mode: replicated
      replicas: 1
    image: graylog/graylog:4.0
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
    restart: unless-stopped
    environment: 
      - TZ=America/Sao_Paulo
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      # echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost/
      - GRAYLOG_MONGODB_URI=mongodb://root:mongo@mongo:27017/graylog?authSource=admin
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      # Graylog web interface and REST API
      - 9001:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - graylog
    volumes:
      - graylog_data:/usr/share/graylog/data
    logging:
      driver: "journald"
      options:
        tag: "{{.DaemonName}}/{{.Name}}/{{.ID}}"
  # logspout:
  #   image: gliderlabs/logspout:latest
  #   restart: unless-stopped
  #   environment: 
  #     - TZ=America/Sao_Paulo
  #     - RETRY_SEND="10"
  #     - LOGSPOUT_MULTILINE=true
  #   volumes:
  #     - /etc/hostname:/etc/host_hostname:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command:
  #     syslog://rsyslog:514
  #   deploy:
  #     #mode: global
  #     resources:
  #       limits:
  #         cpus: '0.20'
  #         memory: 256M
  #       reservations:
  #         memory: 128M
  #   networks:
  #     - graylog
  #   logging:
  #     driver: "journald"
  #     options:
  #       tag: "{{.DaemonName}}/{{.Name}}/{{.ID}}"
  # rsyslog:
  #   image: rsyslog
  #   restart: unless-stopped
  #   hostname: rsyslog
  #   ports:
  #     - 514:514/tcp
  #     - 514:514/udp
  #   cap_add:
  #     - SYSLOG
  #   environment: 
  #     - TZ=America/Sao_Paulo
  #     - LOGSPOUT=ignore
  #   networks:
  #     - graylog
  #   logging:
  #     driver: "journald"
  #     options:
  #       tag: "{{.DaemonName}}/{{.Name}}/{{.ID}}"
  #   networks:
  #     - graylog
  nginx:
    image: nginx:stable
    #entrypoint: /usr/bin/tini -- wait-for-it graylog:9000 -- /docker-entrypoint.sh
    restart: unless-stopped
    environment:
      #- LOGSPOUT=ignore
      - TZ=America/Sao_Paulo
    logging:
      driver: "journald"
      options:
        tag: "{{.DaemonName}}/{{.Name}}/{{.ID}}"
    volumes:
      - $PWD/nginx_default.conf:/etc/nginx/conf.d/default.conf
#      - $PWD/nginx_ssl:/etc/nginx/ssl:ro
    networks:
      - graylog
    ports:
      - 80:80
#      - 443:443
networks:
  graylog:
    external: false
    name: graylog
volumes:
  mongo_data:
  es_data:
  graylog_data:
