version: "3.8"
services:
  spider:
    image: registry.example.com/${IMAGE}:${BUILD_ID}
    ports:
      - 8080:8080
    container_name: spider
    environment:
      - TZ=America/Sao_Paulo
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
          memory: 256M
        reservations:
          memory: 256M
    restart: unless-stopped
    healthcheck:
      test: curl -fsSL http://localhost:9100/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
        tag: "{{.DaemonName}}.{{.ImageName}}"
