version: '3.8'
networks:
  proxy:
    external: 
      name: proxy
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    ports:
      - "9000:9000"
      #- "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
        tag: "{{.DaemonName}}.{{.ImageName}}"
    networks:
      - proxy
volumes:
  portainer_data:
