version: "3.8"
services:
  dns-proxy:
    container_name: dns-proxy
    image: dns-proxy
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
          memory: 128M
        reservations:
          memory: 128M
    environment: 
      - TZ=America/Sao_Paulo
      - update=1
    networks: 
      - proxy
    ports:
      - 127.0.0.1:5353:5353/udp
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
        tag: "{{.DaemonName}}.{{.ImageName}}"
networks:
  proxy:
    name: proxy
    external: true