version: "3.8"
services:
  dns-proxy:
    environment: 
      - TZ=America/Sao_Paulo
      - update=1
    image: dns-proxy
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    container_name: dns-proxy
    networks: 
      - proxy
    ports:
      - 127.0.0.1:5353:5353/udp
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
          memory: 256M
        reservations:
          memory: 128M
    restart: "unless-stopped"
networks:
  proxy:
    name: proxy
    external: true